execute @s ~ ~ ~ detect ~ ~-0.01 ~ clay 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ dirt 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ grass 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ gravel 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ sand 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ soul_sand 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ soul_soil 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ crimson_nylium 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ warped_nylium 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ mud 0 kill @s
execute @s ~ ~ ~ detect ~ ~-0.01 ~ muddy_mangrove_roots 0 kill @s