execute as @a at @s if block ~ ~-0.01 ~ clay run kill @s
execute as @a at @s if block ~ ~-0.01 ~ dirt run kill @s
execute as @a at @s if block ~ ~-0.01 ~ grass run kill @s
execute as @a at @s if block ~ ~-0.01 ~ gravel run kill @s
execute as @a at @s if block ~ ~-0.01 ~ sand run kill @s
execute as @a at @s if block ~ ~-0.01 ~ soul_sand run kill @s
execute as @a at @s if block ~ ~-0.01 ~ soul_soil run kill @s
execute as @a at @s if block ~ ~-0.01 ~ crimson_nylium run kill @s
execute as @a at @s if block ~ ~-0.01 ~ warped_nylium run kill @s
execute as @a at @s if block ~ ~-0.01 ~ mud run kill @s
execute as @a at @s if block ~ ~-0.01 ~ muddy_mangrove_roots run kill @s