execute as @a at @a if block ~ ~-0.01 ~ ice run kill @s
execute as @a at @a if block ~ ~-0.01 ~ packed_ice run kill @s
execute as @a at @a if block ~ ~-0.01 ~ blue_ice run kill @s
execute as @a at @a if block ~ ~-0.01 ~ clay run kill @s
execute as @a at @a if block ~ ~-0.01 ~ deepslate run kill @s
execute as @a at @a if block ~ ~-0.01 ~ dirt run kill @s
execute as @a at @a if block ~ ~-0.01 ~ grass run kill @s
execute as @a at @a if block ~ ~-0.01 ~ gravel run kill @s
execute as @a at @a if block ~ ~-0.01 ~ sand run kill @s
execute as @a at @a if block ~ ~-0.01 ~ snow run kill @s
execute as @a at @a if block ~ ~-0.01 ~ stone run kill @s
execute as @a at @a if block ~ ~-0.01 ~ mud run kill @s
execute as @a at @a if block ~ ~-0.01 ~ muddy_mangrove_roots run kill @s
execute as @a at @a if block ~ ~-0.01 ~ sculk run kill @s at @a
execute as @a at @a if block ~ ~-0.01 ~ snow_layer run kill @s
execute as @a at @a if block ~ ~-0.01 ~ sculk_catalyst run kill @s
execute as @a at @a if block ~ ~-0.01 ~ sculk_sensor run kill @s
execute as @a at @a if block ~ ~-0.01 ~ sculk_shrieker run kill @s
execute as @a at @a if block ~ ~-0.01 ~ calibrated_sculk_sensor run kill @s
execute as @a at @a if block ~ ~-0.01 ~ polished_basalt run kill @s
execute as @a at @a if block ~ ~-0.01 ~ hardened_clay run kill @s